const words = [{word:"pizza", category:"Type of Food"},
{word:"lizard", category:"Animals or insects"},
{word:"peanuts", category:"Type of Food"},
{word:"yogurt", category:"Type of Food"},
{word:"butterfly", category:"Animals or insects"},
{word:"canada", category:"Countries"},
{word:"mexico", category:"Countries"},
{word:"andorra", category:"Countries"},
{word:"nigeria", category:"Countries"},
{word:"mongolia", category:"Countries"},
{word:"germany", category:"Countries"},
{word:"israel", category:"Countries"},
{word:"paraguay", category:"Countries"},
{word:"falcon", category:"Animals or insects"},
{word:"gorilla", category:"Animals or insects"},
{word:"beaver", category:"Animals or insects"},
{word:"squirrel", category:"Animals or insects"},
{word:"lasagna", category:"Type of Food"},
{word:"chocolate", category:"Type of Food"},
{word:"almond", category:"Type of Food"},
{word:"sandwich", category:"Type of Food"},
{word:"blueberry", category:"Type of Food"},
{word:"hamburger", category:"Type of Food"},
{word:"racoon", category:"Animals or insects"},
{word:"paella", category:"Type of Food"},
{word:"seagull", category:"Animals or insect"},
{word:"strawberry", category:"Type of Food"},
{word:"crocodile", category:"Animals or insects"},
{word:"sushi", category:"Type of Food"},
{word:"scotland", category:"Countries"}]